### ISSUE TITLE
Add Specific README.md for /bash/scripts/ folder?

### ISSUE THREAD

**Issue by garzarobm** [umer936/dotfiles#5]
<details><summary>On another note Would it be useful for people to:
</summary>
<p>
i.e. 

- [ ] Add a specific README.md for the scripts folder?
  - [ ] Add general tips on how to manage files in the folder that aren't made for customization
  - [ ] Some example scripts on how to run it periodically (through Cron, Ajax, etc...)

I can create it as a separate pull request?

</p>
</details>

_Originally posted by @garzarobm in https://github.com/umer936/dotfiles/issues/4#issuecomment-2151146908_

**Comment by umer936** [comment]
Don't think that's necessary. These are basically just helper scripts that I run when the situation arises (e.g. discord says an update is required) - not by any cronjob or such
